"""Initial schema

Revision ID: db22112590d1
Revises:
Create Date: 2026-06-12 17:00:35.217445

"""
from alembic import op
import sqlalchemy as sa

# DB_TABLE_PREFIX is read at import time, so these build a prefixed or unprefixed schema
# to match the models either way. table_name also prefixes FK targets
# ("camps.id" -> "<prefix>camps.id"); index_name prefixes auto index names.
from camp_planner.config import table_name, table_name as _fk, index_name as _ix


# revision identifiers, used by Alembic.
revision = 'db22112590d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(table_name('camps'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('length_days', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('window_start_min', sa.Integer(), nullable=False),
    sa.Column('snap_minutes', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timeline_rev', sa.Integer(), server_default='0', nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('google_sync_token', sa.Text(), nullable=True),
    sa.Column('google_last_pull_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('camps'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_camps_slug')), ['slug'], unique=True)

    op.create_table(table_name('users'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('users'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_users_username')), ['username'], unique=True)

    op.create_table(table_name('categories'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'key', name='uq_category_camp_key')
    )
    op.create_table(table_name('materials'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'normalized_name', name='uq_material_camp_norm')
    )
    with op.batch_alter_table(table_name('materials'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_materials_normalized_name')), ['normalized_name'], unique=False)

    op.create_table(table_name('orgs'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('initials', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'initials', name='uq_org_camp_initials')
    )
    with op.batch_alter_table(table_name('orgs'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_orgs_external_id')), ['external_id'], unique=False)

    op.create_table(table_name('tags'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('label', 'check', 'progress', 'text', name='tag_kind', native_enum=False), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'name', name='uq_tag_camp_name')
    )
    op.create_table(table_name('user_camp_roles'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('editor', 'viewer', name='camp_role', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [_fk('users.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'camp_id', 'role', name='uq_user_camp_role')
    )
    with op.batch_alter_table(table_name('user_camp_roles'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_user_camp_roles_camp_id')), ['camp_id'], unique=False)

    op.create_table(table_name('activities'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('basic', 'external', 'external_lecture', name='activity_type', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.ForeignKeyConstraint(['category_id'], [_fk('categories.id')], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('activities'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_activities_camp_id')), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_activities_category_id')), ['category_id'], unique=False)

    op.create_table(table_name('activity_assignments'),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('garant', 'helper', name='org_role', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ),
    sa.ForeignKeyConstraint(['org_id'], [_fk('orgs.id')], ),
    sa.PrimaryKeyConstraint('activity_id', 'org_id', 'role')
    )
    with op.batch_alter_table(table_name('activity_assignments'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_activity_assignments_org_id')), ['org_id'], unique=False)

    op.create_table(table_name('activity_tags'),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], [_fk('tags.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'tag_id')
    )
    with op.batch_alter_table(table_name('activity_tags'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_activity_tags_tag_id')), ['tag_id'], unique=False)

    op.create_table(table_name('audit_logs'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('camp', 'activity', 'timeline', 'assignment', 'slot_assignment', 'tag', 'todo', 'material', 'material_need', 'category', 'org', name='entity_type', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', name='audit_action', native_enum=False), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('audit_logs'), schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_audit_logs_activity_id')), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_audit_logs_author')), ['author'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_audit_logs_camp_id')), ['camp_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_audit_logs_created_at')), ['created_at'], unique=False)

    op.create_table(table_name('material_needs'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ),
    sa.ForeignKeyConstraint(['material_id'], [_fk('materials.id')], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'material_id', name='uq_material_need')
    )
    with op.batch_alter_table(table_name('material_needs'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_material_needs_material_id')), ['material_id'], unique=False)

    op.create_table(table_name('slots'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('main', 'prep', 'cleanup', name='slot_role', native_enum=False), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.CheckConstraint('end_at > start_at', name='ck_slot_time_order'),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('slots'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_slots_activity_id')), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_slots_google_event_id')), ['google_event_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_slots_start_at')), ['start_at'], unique=False)

    op.create_table(table_name('todos'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], [_fk('activities.id')], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('todos'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_todos_activity_id')), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f(_ix('ix_todos_due_date')), ['due_date'], unique=False)

    op.create_table(table_name('slot_assignments'),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], [_fk('orgs.id')], ),
    sa.ForeignKeyConstraint(['slot_id'], [_fk('slots.id')], ),
    sa.PrimaryKeyConstraint('slot_id', 'org_id')
    )
    with op.batch_alter_table(table_name('slot_assignments'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_slot_assignments_org_id')), ['org_id'], unique=False)

    op.create_table(table_name('google_sync_ops'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('op', sa.Enum('upsert', 'delete', name='google_sync_op', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], [_fk('camps.id')], ),
    sa.ForeignKeyConstraint(['slot_id'], [_fk('slots.id')], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(table_name('google_sync_ops'), schema=None) as batch_op:
        batch_op.create_index(batch_op.f(_ix('ix_google_sync_ops_camp_id')), ['camp_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(table_name('google_sync_ops'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_google_sync_ops_camp_id')))

    op.drop_table(table_name('google_sync_ops'))
    with op.batch_alter_table(table_name('slot_assignments'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_slot_assignments_org_id')))

    op.drop_table(table_name('slot_assignments'))
    with op.batch_alter_table(table_name('todos'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_todos_due_date')))
        batch_op.drop_index(batch_op.f(_ix('ix_todos_activity_id')))

    op.drop_table(table_name('todos'))
    with op.batch_alter_table(table_name('slots'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_slots_start_at')))
        batch_op.drop_index(batch_op.f(_ix('ix_slots_google_event_id')))
        batch_op.drop_index(batch_op.f(_ix('ix_slots_activity_id')))

    op.drop_table(table_name('slots'))
    with op.batch_alter_table(table_name('material_needs'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_material_needs_material_id')))

    op.drop_table(table_name('material_needs'))
    with op.batch_alter_table(table_name('audit_logs'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_audit_logs_created_at')))
        batch_op.drop_index(batch_op.f(_ix('ix_audit_logs_camp_id')))
        batch_op.drop_index(batch_op.f(_ix('ix_audit_logs_author')))
        batch_op.drop_index(batch_op.f(_ix('ix_audit_logs_activity_id')))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table(table_name('audit_logs'))
    with op.batch_alter_table(table_name('activity_tags'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_activity_tags_tag_id')))

    op.drop_table(table_name('activity_tags'))
    with op.batch_alter_table(table_name('activity_assignments'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_activity_assignments_org_id')))

    op.drop_table(table_name('activity_assignments'))
    with op.batch_alter_table(table_name('activities'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_activities_category_id')))
        batch_op.drop_index(batch_op.f(_ix('ix_activities_camp_id')))

    op.drop_table(table_name('activities'))
    with op.batch_alter_table(table_name('user_camp_roles'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_user_camp_roles_camp_id')))

    op.drop_table(table_name('user_camp_roles'))
    op.drop_table(table_name('tags'))
    with op.batch_alter_table(table_name('orgs'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_orgs_external_id')))

    op.drop_table(table_name('orgs'))
    with op.batch_alter_table(table_name('materials'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_materials_normalized_name')))

    op.drop_table(table_name('materials'))
    op.drop_table(table_name('categories'))
    with op.batch_alter_table(table_name('users'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_users_username')))

    op.drop_table(table_name('users'))
    with op.batch_alter_table(table_name('camps'), schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(_ix('ix_camps_slug')))

    op.drop_table(table_name('camps'))
    # ### end Alembic commands ###
